version: '3.8'

services:
  btg_otp_test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app 
    command: sh -c "npm install && npm run dev"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"